export { BaseMail, DEFAULT_BASE_URL } from './client';
export { BaseMailError } from './errors';
export type {
  AccountSettings,
  ApiErrorBody,
  ApiKeyInfo,
  Attachment,
  AttachmentInfo,
  AttnBalance,
  AttnClaimResult,
  AttnHistoryOptions,
  AttnHistoryResult,
  AttnSettings,
  AttnTransaction,
  AuthResult,
  BaseMailOptions,
  CreateKeyOptions,
  CreateKeyResult,
  Email,
  EmailDetail,
  Folder,
  Handle,
  Identity,
  InboxOptions,
  InboxResult,
  MarkReadOptions,
  MarkReadResult,
  RefreshResult,
  RegisterOptions,
  RevokeKeyOptions,
  SendOptions,
  SendResult,
  UnixSeconds,
  VerifyResult,
  Webhook,
  WebhookCreated,
  WebhookCreateOptions,
} from './types';
